import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Sidebar for dev-docs/.
 * Generated from the folder structure; order is controlled by
 * `sidebar_position` in each doc and `_category_.json` in each folder.
 */
const sidebars: SidebarsConfig = {
  devSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
